version: "3"
services:
  nginx:
    image: nginx:1.13.7
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - appa
      - appb
  appa:
    hostname: appa
    build:
      context: .
      dockerfile: appa/Dockerfile
    entrypoint:
      - flask
      - run
      - --host=${HOST}
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - ${APPA_PORT}:${APPA_PORT}
    volumes: [".:/app"]
  appb:
    hostname: appb
    build:
      context: .
      dockerfile: appb/Dockerfile
    entrypoint:
      - flask
      - run
      - --host=${HOST}
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - ${APPB_PORT}:${APPB_PORT}
    volumes: [".:/app"]