version: "3"
services:
  nginx:
    image: nginx:1.13.7
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-a
      - app-b
  app-a:
    hostname: appa
    build:
      context: .
      dockerfile: app-a/Dockerfile
    entrypoint:
      - flask
      - run
      - --host=${HOST}
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - ${APPA_PORT}:${APPA_PORT}
    volumes: [".:/app"]
  app-b:
    hostname: appb
    build:
      context: .
      dockerfile: app-b/Dockerfile
    entrypoint:
      - flask
      - run
      - --host=${HOST}
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - ${APPB_PORT}:${APPB_PORT}
    volumes: [".:/app"]